### ISSUE TITLE
Cannot run testing on WSL2 / Ubuntu 20.04

### ISSUE THREAD

**Issue by j-cortial** [jeff-hykin/better-cpp-syntax#615]
When running the command `project test` I get the following error :
```
Error: /nix/store/5lgyy30nyvq59c4m2a7skmwaqz3jja3n-gcc-10.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by better-cpp-syntax/node_modules/.pnpm/oniguruma@7.2.3/node_modules/oniguruma/build/Release/onig_scanner.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (better-cpp-syntax/node_modules/.pnpm/oniguruma@7.2.3/node_modules/oniguruma/src/oniguruma.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
```

My setup is Ubuntu 20.04 installed on WSL2.

**Comment by jeff-hykin** [comment]
Sorry about that, and thanks for reporting this as it actually affects serveral of my repos.

Pulling the latest master, doing `commands/start` then `project purge;exit` followed by another `commands/start` should get everything back in working shape

**Comment by j-cortial** [comment]
Problem solved.
